name: Android Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  android_tests:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create google-services.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "google-services.json"
          json: ${{ secrets.GOOGLE_SERVICES_JSON }}
          dir: 'app/'

      - name: Install scrcpy
        run: brew install scrcpy

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            ./gradlew connectedAndroidTest
            scrcpy --no-display --max-size 1024 --max-fps 15 --record=scrcpy_record.mp4

      - name: Stop scrcpy
        if: always()
        run: killall scrcpy

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: app/build/reports/androidTests/
          retention-days: 7

      - name: Upload screen record
        uses: actions/upload-artifact@v3
        with:
          name: screen-record
          path: scrcpy_record.mp4
          retention-days: 1
