name: Android Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  android_tests_ftl:
    runs-on: [macos-latest]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Authenticate
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 420.0.0'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create google-services.json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "google-services.json"
          json: ${{ secrets.GOOGLE_SERVICES_JSON }}
          dir: 'app/'

      - name: Build
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - name: Run Tests
        run: |
          gcloud beta firebase test android run \
            --quiet
            --type instrumentation \
            --app app/build/outputs/apk/debug/app-debug.apk \
            --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --use-orchestrator \
            --num-uniform-shards=4 \
            --environment-variables clearPackageData=true
